meta_product_name: "Looking Good"
meta_title: "Looking Good - Rental Products website"
meta_description: "Save money and make extra money renting products online!"
meta_image: "photo-metatag.png" # should exist in `app/assets/images/`
